seqtabnochim_mbwrpf <- read.csv("file:///C:/Users/egger/Desktop/mbwrpf/seqtabnochim_mbwrpf.txt", sep="")
View(seqtabnochim_mbwrpf)
taxa_mbwrpf <- read.csv("file:///C:/Users/egger/Desktop/mbwrpf/taxa_mbwrpf.txt", sep="")
View(taxa_mbwrpf)
tracking_mbwrpf <- read.csv("file:///C:/Users/egger/Desktop/mbwrpf/tracking_mbwrpf.txt", sep="")
View(tracking_mbwrpf)
library(phyloseq); packageVersion("phyloseq")
library(Biostrings); packageVersion("Biostrings")
library(ggplot2); packageVersion("ggplot2")
mbwrpf_otu <- as.matrix(seqtabnochim_mbwrpf)
mbwrpf_taxa <- as.matrix(taxa_mbwrpf)
library(readxl)
View(metadata)
row.names(metadata) <- metadata$Sample
View(metadata)
mbwrpfps <- phyloseq(otu_table(mbwrpf_otu, taxa_are_rows=FALSE), sample_data(metadata), tax_table(mbwrpf_taxa))
mbwrpfps
dna <- Biostrings::DNAStringSet(taxa_names(mbwrpfps))
mbwrpfps <- merge_phyloseq(mbwrpfps, dna)
taxa_names(mbwrpfps) <- paste0("ASV", seq(ntaxa(mbwrpfps)))
library(file2meco)
mbwrpf_meco <- phyloseq2meco(mbwrpfps)
mbwrpf_meco
library(microeco)
library(ggplot2)
theme_set(theme_bw())

mbwrpf_meco$sample_sums()
mbwrpf_meco$rarefy_samples(sample.size = 10000)
mbwrpf_meco$cal_abund()
class(mbwrpf_meco$taxa_abund)
dir.create("taxa_abund")
mbwrpf_meco$save_abund(dirpath = "taxa_abund")
mbwrpf_meco$cal_alphadiv(PD = FALSE)
class(mbwrpf_meco$alpha_diversity)
dir.create("alpha_diversity")
mbwrpf_meco$save_alphadiv(dirpath = "alpha_diversity")

mbwrpf_meco$Diet <- factor(mbwrpf_meco$Diet, levels=c("CC", "PF", "WR", "BR"))
mbwrpf_meco$cal_betadiv(unifrac = FALSE)
class(mbwrpf_meco$beta_diversity)
dir.create("beta_diversity")
mbwrpf_meco$save_betadiv(dirpath = "beta_diversity")

#don't run
abund1 <- trans_abund$new(dataset = mbwrpf_meco, taxrank = "Phylum", ntaxa = 10)
abund1$plot_bar(others_color = "grey70", facet = "Diet", xtext_keep = FALSE, legend_text_italic = FALSE)

abund_phyla1 <- trans_abund$new(dataset = mbwrpf_meco, taxrank = "Phylum", ntaxa = 10, groupmean = "Diet")
abund_phyla1$plot_bar(others_color = "grey70", legend_text_italic = FALSE)

abund_class1 <- trans_abund$new(dataset = mbwrpf_meco, taxrank = "Class", ntaxa = 15)
abund_class1$plot_box(group = "Diet")

abund_genus1 <- trans_abund$new(dataset = mbwrpf_meco, taxrank = "Genus", ntaxa = 40)
abund_genus1$plot_heatmap(facet = "Diet", xtext_keep = FALSE, withmargin = FALSE)

#missing numbers
dataset1 <- mbwrpf_meco$merge_samples(use_group = "Diet")
venn1 <- trans_venn$new(dataset1, ratio = "seqratio")
venn1$plot_venn(petal_plot=TRUE)

bray1 <- trans_beta$new(dataset = mbwrpf_meco, group = "Diet", measure = "bray")
bray1$cal_ordination(ordination = "PCoA")
class(bray1$res_ordination)
bray1 <- bray1$plot_ordination(plot_color = "Diet", plot_shape = "Diet", plot_group_ellipse = TRUE, plot_group_order = c("CC", "PF", "WR", "BR"))
bray1
bray1 + scale_color_manual(values=c("#3DB44B", "#16A0F3", "#F27900", "#EEEE00")) + scale_fill_manual(values=c("#3DB44B", "#16A0F3", "#F27900", "#EEEE00"))



joey_colors=c("#3DB44B", "#16A0F3", "#F27900", "#EEEE00")



library(ggpubr)
t1$cal_group_distance()
t1$plot_group_distance(distance_pair_stat = TRUE)
t1$cal_group_distance(within_group = FALSE)
t1$plot_group_distance(distance_pair_stat = TRUE)
library(ggdendro)
t1$plot_clustering(group = "Diet")
t1$cal_manova(cal_manova_all = TRUE)
t1$res_manova$aov.tab
t1$res_manova
t1$cal_betadisper()
t1$res_betadisper
mbwrpf_akker <- trans_abund$new(dataset = mbwrpf_meco, taxrank = "Genus", input_taxaname="Akkermansia", ntaxa = 10)
mbwrpf_akker$plot_box(group = "Diet")
mbwrpf_prevo <- trans_abund$new(dataset = mbwrpf_meco, taxrank = "Genus", input_taxaname="Prevotella", ntaxa = 10)
mbwrpf_prevo$plot_box(group = "Diet")
mbwrpf_lacto <- trans_abund$new(dataset = mbwrpf_meco, taxrank = "Genus", input_taxaname="Lactobacillus", ntaxa = 10)
mbwrpf_lacto$plot_box(group = "Diet")
mbwrpf_firmi <- trans_abund$new(dataset = mbwrpf_meco, taxrank = "Phylum", input_taxaname="Firmicutes", ntaxa = 10)
mbwrpf_firmi$plot_box(group = "Diet")
mbwrpf_bacter <- trans_abund$new(dataset = mbwrpf_meco, taxrank = "Genus", input_taxaname="Bacteroides", ntaxa = 10)
mbwrpf_bacter$plot_box(group = "Diet")
mbwrpf_bifido <- trans_abund$new(dataset = mbwrpf_meco, taxrank = "Genus", input_taxaname="Bifidobacterium", ntaxa = 10)
mbwrpf_bifido$plot_box(group = "Diet")
mbwrpf_bacteroidota <- trans_abund$new(dataset = mbwrpf_meco, taxrank = "Phylum", input_taxaname="Bacteroidota", ntaxa = 10)
mbwrpf_bacteroidota$plot_box(group = "Diet")
mbwrpf_alistipes <- trans_abund$new(dataset = mbwrpf_meco, taxrank = "Genus", input_taxaname="Alistipes", ntaxa = 10)
mbwrpf_alistipes$plot_box(group = "Diet")
mbwrpf_faeca <- trans_abund$new(dataset = mbwrpf_meco, taxrank = "Genus", input_taxaname="Faecalibaculum", ntaxa = 10)
mbwrpf_faeca$plot_box(group = "Diet")
mbwrpf_roseb <- trans_abund$new(dataset = mbwrpf_meco, taxrank = "Genus", input_taxaname="Roseburia", ntaxa = 10)
mbwrpf_roseb$plot_box(group = "Diet")
mbwrpf_strep <- trans_abund$new(dataset = mbwrpf_meco, taxrank = "Genus", input_taxaname="Streptococcus", ntaxa = 10)
mbwrpf_strep$plot_box(group = "Diet")
mbwrpf_intest <- trans_abund$new(dataset = mbwrpf_meco, taxrank = "Genus", input_taxaname="Intestinimonas", ntaxa = 10)
mbwrpf_intest$plot_box(group = "Diet")
mbwrpf_bilo <- trans_abund$new(dataset = mbwrpf_meco, taxrank = "Genus", input_taxaname="Bilophila", ntaxa = 10)
mbwrpf_bilo$plot_box(group = "Diet")
mbwrpf_prev9 <- trans_abund$new(dataset = mbwrpf_meco, taxrank = "Genus", input_taxaname="Prevotella_9", ntaxa = 10)
mbwrpf_prev9$plot_box(group = "Diet")
mbwrpf_blautia <- trans_abund$new(dataset = mbwrpf_meco, taxrank = "Genus", input_taxaname="Blautia", ntaxa = 10)
mbwrpf_blautia$plot_box(group = "Diet")
mbwrpf_allop <- trans_abund$new(dataset = mbwrpf_meco, taxrank = "Genus", input_taxaname="Alloprevotella", ntaxa = 10)
mbwrpf_allop$plot_box(group = "Diet")
mbwrpf_dorea <- trans_abund$new(dataset = mbwrpf_meco, taxrank = "Genus", input_taxaname="Dorea", ntaxa = 10)
mbwrpf_dorea$plot_box(group = "Diet")
mbwrpf_rumin <- trans_abund$new(dataset = mbwrpf_meco, taxrank = "Genus", input_taxaname="Ruminococcus", ntaxa = 10)
mbwrpf_rumin$plot_box(group = "Diet")
mbwrpf_osc <- trans_abund$new(dataset = mbwrpf_meco, taxrank = "Genus", input_taxaname="Oscillibacter", ntaxa = 10)
mbwrpf_osc$plot_box(group = "Diet")
